config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :predictors
  resources :fighters
  resources :events, shallow: true do
    resources :fights
    resources :predictions, only: :index
  end
  resources :fights, shallow: true do
    resources :predictions, only: %i[create update destroy]
  end
end

app/models/predictor.rb
class Predictor < ApplicationRecord
  belongs_to :account, class_name: 'User', optional: true
  has_many :predictions

  scope :search, ->(query='') { where 'name ILIKE :q', q: "%#{query}%" }
end

app/controllers/predictors_controller.rb
class PredictorsController < ApplicationController

  def index
    @predictors = Predictor.search(params[:query])
    respond_to do |format|
      format.html
    end
  end

  def show
    @predictor = Predictor.find params[:id]
    respond_to do |format|
      format.html
    end
  end

  def new
    form Predictor::Create
    respond_to do |format|
      format.html
    end
  end

  def create
    respond_to do |format|
      run Predictor::Create do |op|
        format.html { return redirect_to op.model }
      end
      format.html { render :new }
    end
  end

  def edit
    form Predictor::Update
    respond_to do |format|
      format.html
    end
  end

  def update
    respond_to do |format|
      run Predictor::Update do |op|
        format.html { return redirect_to op.model }
      end
      format.html { render :edit }
    end
  end

  def destroy
    respond_to do |format|
      run Predictor::Destroy do |_|
      end
      format.html { redirect_to predictors_url }
    end
  end
end

app/views/predictors/_form.html.slim
= simple_form_for form do |f|
  = f.input :name
  = f.button :submit

app/views/predictors/edit.html.slim
h3
  = t '.title'

= render 'form', form: @form

app/views/predictors/index.html.slim
h3
  = t '.title'
  small =< link_to t('predictors.new.title'), new_predictor_path

table.table.table-hover
  thead
    tr
      th = Predictor.human_attribute_name(:name)
      th

  tbody
    - @predictors.each do |predictor|
      tr
        td = link_to predictor.name, predictor_path(predictor)
        td: .btn-group.btn-group-xs
          = link_to icon(:edit), edit_predictor_path(predictor), class: 'btn btn-default'
          = link_to icon(:trash), predictor, data: {confirm: t('helpers.confirmation')}, method: :delete, class: 'btn btn-danger'

app/views/predictors/new.html.slim
h3
  = t '.title'

= render 'form', form: @form

app/views/predictors/show.html.slim
h3 = @predictor.name